---
title: "Predictions"
author: "James Bury"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(randomForest)
library(glmnet)
```

```{r}
df = read.csv("DF_FINAL_CONFERENCES_DIFFS.csv")
conference_games = data.frame(Conference="", Games=0)
for(l in levels(df$Conference)) {
  print(l)
  print(nrow(df %>% filter(Conference == l)))
  conference_games = rbind(conference_games, data.frame(Conference=l, Games=nrow(df %>% filter(Conference == l))))
}
conference_games = conference_games[-1,]
conference_games
write.csv(file = 'games_per_conference.csv', conference_games)
```

```{r}
head(df)
```

### NOTES: did not include l = 6 of the conferences because FBS Independent does not have enough games

# Predicting Result

# Make prediction set
```{r}
set.seed(1234)

train = list()
test = list()
dfs = list()

for(l in 1:length(levels(df$Conference))) {
  df.prediction = df %>%
    filter(Conference == levels(df$Conference)[l]) %>%
    select(
      -School,
      -Opponent,
      -Date,
      -Season,
      -Score,
      -OppScore,
      -Total,
      -Spread,
      -Conference,
      -SeasonRanking,
      -OppSeasonRanking,
      -Team,
      -Nickname,
      -City,
      -State,
      -OppNickname,
      -OppCity,
      -OppState,
      -OppConference)

  df.prediction$Outcome = ifelse(df.prediction$Outcome == "W", 1, 0)
  df.prediction$Season.Type = ifelse(df.prediction$Season.Type == "Regular", 1, 0)
  
  curr_train = sample_n(df.prediction, size = 0.7 * nrow(df.prediction), replace = FALSE)
  train[[l]] = data.frame(curr_train)
  test[[l]] = data.frame(anti_join(df.prediction, curr_train))
}


```

# Logistic Regression
```{r}
set.seed(1234)

accuracies = data.frame(Conference="", Accuracy=0)
for(l in 1:length(train)) {
  if(length(test[[l]]) > 20) {
    model = glm(Outcome~., data = train[[l]], family = "binomial")
    predictions = suppressWarnings(predict.glm(model, test[[l]], type = "response"))
    predictions = ifelse(predictions >= 0.5, 1, 0)
    print(paste("Logistic Regression Accuracy on 30% test",sum(ifelse(predictions == test[[l]]$Outcome, 1, 0)) / nrow(test[[l]])))
    accuracies = rbind(accuracies, data.frame(Conference=levels(df$Conference)[l], Accuracy=sum(ifelse(predictions == test[[l]]$Outcome, 1, 0)) / nrow(test[[l]])))
  }
}
accuracies = accuracies[-1,]
accuracies

```

# Predicting Spread

# Make prediction set
```{r}
df = read.csv('df_spread.csv')
set.seed(1234)

train = list()
test = list()
dfs = list()

for(l in 1:length(levels(df$Conference))) {

  df.prediction = df %>%
    filter(Conference == levels(df$Conference)[l])

  curr_train = sample_n(df.prediction, size = 0.7 * nrow(df.prediction), replace = FALSE)
  train[[l]] = data.frame(curr_train)
  test[[l]] = data.frame(anti_join(df.prediction, curr_train))

}
```

# Random Forest Regression
```{r}
set.seed(1234)


for(l in 1:length(train)) {
  if(length(test[[l]]) > 20) {
    l = 1
    curr_train = train[[l]]
    curr_test = test[[l]]
    rf = randomForest(select(curr_train, -Spread), y = as.factor(curr_train$Spread), xtest = select(curr_test, -Spread), ytest = as.factor(curr_test$Outcome), keep.forest = TRUE)
    rf
    print("Random Forest Regression Accuracy on 30% test")
    importance(rf)
  }
}

```


# Linear Regression
```{r}
set.seed(1234)

accuracies = data.frame(Conference="", MAE=0)
for(l in 1:length(train)) {
  if(length(test[[l]]) > 20) {
    model = lm(Spread~., data = train[[l]])
    print(summary(model))
    predictions = predict.lm(model, newdata = test[[l]], type = "response")
    MAE = sum(abs(test[[l]]$Spread - predictions)) / nrow(test[[l]])
    print(paste("Linear Regression MAE on 30% test",MAE))
    accuracies = rbind(accuracies, data.frame(Conference=levels(df$Conference)[l], MAE=MAE))
  }
}
accuracies = accuracies[-1,]
write.csv(file = 'linear_spread.csv', accuracies)
```

# Lasso Regression
```{r}

set.seed(1234)

accuracies = data.frame(Conference="", MAE=0)
for(l in 1:length(train)) {
  if(l != 6) {
    train.matrix = model.matrix(Spread~., data = train[[l]])
    test.matrix = model.matrix(Spread~., data = test[[l]])
    model = cv.glmnet(train.matrix, train[[l]]$Spread, alpha = 1, nfolds = 5)
    predictions = predict.cv.glmnet(model, newx = test.matrix, type = "response")
    MAE = sum(abs(test[[l]]$Spread - predictions)) / nrow(test[[l]])
    MAE
    print(paste("Lasso Regression MAE on 30% test",MAE))
    accuracies = rbind(accuracies, data.frame(Conference=levels(df$Conference)[l], MAE=MAE))
  }
}
accuracies = accuracies[-1,]
accuracies
write.csv(file = 'lasso_spread.csv', accuracies)

```


# Predicting Total

# Make prediction set
```{r}
set.seed(1234)

train = list()
test = list()
dfs = list()

for(l in 1:length(levels(df$Conference))) {

  df.prediction = df %>%
    filter(Conference == levels(df$Conference)[l]) %>%
    select(
      -School,
      -Opponent,
      -Date,
      -Season,
      -Score,
      -OppScore,
      -Outcome,
      -Spread,
      -SeasonRanking,
      -OppSeasonRanking,
      -Team,
      -Nickname,
      -City,
      -State,
      -Conference,
      -OppNickname,
      -OppCity,
      -OppState,
      -OppConference)
  
  df.prediction$Season.Type = ifelse(df.prediction$Season.Type == "Regular", 1, 0)

  curr_train = sample_n(df.prediction, size = 0.7 * nrow(df.prediction), replace = FALSE)
  train[[l]] = data.frame(curr_train)
  test[[l]] = data.frame(anti_join(df.prediction, curr_train))

}
```

# Linear Model
```{r}
set.seed(1234)

accuracies = data.frame(Conference="", MAE=0)

for(l in 1:length(train)) {
  if(length(test[[l]]) > 20) {
    model = lm(Total~., data = train[[l]])
    print(summary(model))
    predictions = predict.lm(model, newdata = test[[l]], type = "response")
    MAE = sum(abs(test[[l]]$Total - predictions)) / nrow(test[[l]])
    print(paste("Linear Regression MAE on 30% test",MAE))
    accuracies = rbind(accuracies, data.frame(Conference=levels(df$Conference)[l], MAE=MAE))
  }
}
accuracies = accuracies[-1,]
write.csv(file = 'linear_total.csv', accuracies)
```

# Lasso Regression
```{r}
set.seed(1234)

accuracies = data.frame(Conference="", MAE=0)
for(l in 1:length(train)) {
  if(l != 6) {
    train.matrix = model.matrix(Total~., data = train[[l]])
    test.matrix = model.matrix(Total~., data = test[[l]])
    model = cv.glmnet(train.matrix, train[[l]]$Total, family = "gaussian", alpha = 0, nfolds = 5)
    predictions = predict.cv.glmnet(model, newx = test.matrix, type = "response")
    MAE = sum(abs(test[[l]]$Total - predictions)) / nrow(test[[l]])
    MAE
    print(paste("Lasso Regression MAE on 30% test",MAE))
    accuracies = rbind(accuracies, data.frame(Conference=levels(df$Conference)[l], MAE=MAE))
  }
}
accuracies = accuracies[-1,]
accuracies
write.csv(file = 'lasso_total.csv', accuracies)
```

